## **Names:** 
## Shams Hossam Zayan &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6854
## Youmna Mohamed Elmezayen &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6887 
## Maryam Abdou Abdelfattah &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7071

# **Network Anomaly**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.neighbors import kneighbors_graph
from sklearn.cluster import KMeans
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

test = pd.read_csv('/corrected.gz', compression='gzip', header=0, sep=',', quotechar='"')
train = pd.read_csv('/kddcup.data_10_percent.gz', compression='gzip', header=0, sep=',', quotechar='"')
cols = train.columns

In [ ]:
train.head(10)

,0,tcp,http,SF,181,5450,0.1,0.2,0.3,0.4,...,9.1,1.00.1,0.00.6,0.11,0.00.7,0.00.8,0.00.9,0.00.10,0.00.11,normal.
0,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.00,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.00,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.00,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.00,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,59,1.0,0.0,0.02,0.00,0.0,0.0,0.0,0.0,normal.
5,0,tcp,http,SF,212,1940,0,0,0,0,...,69,1.0,0.0,1.00,0.04,0.0,0.0,0.0,0.0,normal.
6,0,tcp,http,SF,159,4087,0,0,0,0,...,79,1.0,0.0,0.09,0.04,0.0,0.0,0.0,0.0,normal.
7,0,tcp,http,SF,210,151,0,0,0,0,...,89,1.0,0.0,0.12,0.04,0.0,0.0,0.0,0.0,normal.
8,0,tcp,http,SF,212,786,0,0,0,1,...,99,1.0,0.0,0.12,0.05,0.0,0.0,0.0,0.0,normal.
9,0,tcp,http,SF,210,624,0,0,0,0,...,109,1.0,0.0,0.06,0.05,0.0,0.0,0.0,0.0,normal.

In [ ]:
test.head(10)

,0,udp,private,SF,105,146,0.1,0.2,0.3,0.4,...,254,1.00.1,0.01,0.00.6,0.00.7,0.00.8,0.00.9,0.00.10,0.00.11,normal.
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.0,0.0,normal.
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.0,0.0,normal.
2,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.0,0.0,snmpgetattack.
3,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.0,0.0,0.0,0.0,snmpgetattack.
4,0,udp,private,SF,105,146,0,0,0,0,...,255,1.00,0.00,0.01,0.00,0.0,0.0,0.0,0.0,snmpgetattack.
5,0,udp,domain_u,SF,29,0,0,0,0,0,...,3,0.30,0.30,0.30,0.00,0.0,0.0,0.0,0.0,normal.
6,0,udp,private,SF,105,146,0,0,0,0,...,253,0.99,0.01,0.00,0.00,0.0,0.0,0.0,0.0,normal.
7,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.0,0.0,snmpgetattack.
8,0,tcp,http,SF,223,185,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.0,0.0,0.0,0.0,normal.
9,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.0,0.0,snmpgetattack.

## **Drop extra data in test**

In [ ]:
cond = test['normal.'].isin(train['normal.'])
test.drop(test[cond==False].index, inplace = True)

In [ ]:
test.head(10)

,0,udp,private,SF,105,146,0.1,0.2,0.3,0.4,...,254,1.00.1,0.01,0.00.6,0.00.7,0.00.8,0.00.9,0.00.10,0.00.11,normal.
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal.
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal.
5,0,udp,domain_u,SF,29,0,0,0,0,0,...,3,0.30,0.30,0.30,0.00,0.00,0.0,0.00,0.00,normal.
6,0,udp,private,SF,105,146,0,0,0,0,...,253,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal.
8,0,tcp,http,SF,223,185,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,normal.
10,0,tcp,http,SF,230,260,0,0,0,0,...,255,1.00,0.00,0.33,0.07,0.33,0.0,0.00,0.00,normal.
11,0,udp,private,SF,105,146,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.00,0.0,0.00,0.00,normal.
13,1,tcp,smtp,SF,3170,329,0,0,0,0,...,39,0.72,0.11,0.02,0.00,0.02,0.0,0.09,0.13,normal.
14,0,tcp,http,SF,297,13787,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,normal.
15,0,tcp,http,SF,291,3542,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,normal.

## **Encoding**

In [ ]:
df1 = train[['tcp', 'http', 'SF', 'normal.']].copy()
df2 = test[['udp', 'private', 'SF', 'normal.']].copy()
total= pd.concat([df1, df2.rename(columns={'udp':'tcp', 'private':'http'})], ignore_index=True)

total_columns = ['tcp', 'http', 'SF', 'normal.']
for i in total_columns:
  total[i] = total[i].astype('category')
  total[i] = total[i].cat.codes

df1 = total.iloc[:df1.shape[0],:]
df2 = total.iloc[df1.shape[0]:,:]

train_columns = ['tcp', 'http', 'SF', 'normal.']
test_columns = ['udp', 'private', 'SF', 'normal.']

for i in train_columns:
  train[i] = df1[i]

df2 = df2.rename(columns={'tcp':'udp', 'http':'private'})
df2 = df2.reset_index()
test = test.reset_index(drop=True)
for j in test_columns:
  test[j] = df2[j]

In [ ]:
train.head(10)

,0,tcp,http,SF,181,5450,0.1,0.2,0.3,0.4,...,9.1,1.00.1,0.00.6,0.11,0.00.7,0.00.8,0.00.9,0.00.10,0.00.11,normal.
0,0,1,22,9,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.00,0.0,0.0,0.0,0.0,11
1,0,1,22,9,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.00,0.0,0.0,0.0,0.0,11
2,0,1,22,9,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.00,0.0,0.0,0.0,0.0,11
3,0,1,22,9,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.00,0.0,0.0,0.0,0.0,11
4,0,1,22,9,217,2032,0,0,0,0,...,59,1.0,0.0,0.02,0.00,0.0,0.0,0.0,0.0,11
5,0,1,22,9,212,1940,0,0,0,0,...,69,1.0,0.0,1.00,0.04,0.0,0.0,0.0,0.0,11
6,0,1,22,9,159,4087,0,0,0,0,...,79,1.0,0.0,0.09,0.04,0.0,0.0,0.0,0.0,11
7,0,1,22,9,210,151,0,0,0,0,...,89,1.0,0.0,0.12,0.04,0.0,0.0,0.0,0.0,11
8,0,1,22,9,212,786,0,0,0,1,...,99,1.0,0.0,0.12,0.05,0.0,0.0,0.0,0.0,11
9,0,1,22,9,210,624,0,0,0,0,...,109,1.0,0.0,0.06,0.05,0.0,0.0,0.0,0.0,11

In [ ]:
test.head(10)

,0,udp,private,SF,105,146,0.1,0.2,0.3,0.4,...,254,1.00.1,0.01,0.00.6,0.00.7,0.00.8,0.00.9,0.00.10,0.00.11,normal.
0,0,2,46,9,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.00,0.0,0.00,0.00,11
1,0,2,46,9,105,146,0,0,0,0,...,254,1.00,0.01,0.00,0.00,0.00,0.0,0.00,0.00,11
2,0,2,11,9,29,0,0,0,0,0,...,3,0.30,0.30,0.30,0.00,0.00,0.0,0.00,0.00,11
3,0,2,46,9,105,146,0,0,0,0,...,253,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,11
4,0,1,22,9,223,185,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,11
5,0,1,22,9,230,260,0,0,0,0,...,255,1.00,0.00,0.33,0.07,0.33,0.0,0.00,0.00,11
6,0,2,46,9,105,146,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.00,0.0,0.00,0.00,11
7,1,1,51,9,3170,329,0,0,0,0,...,39,0.72,0.11,0.02,0.00,0.02,0.0,0.09,0.13,11
8,0,1,22,9,297,13787,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,11
9,0,1,22,9,291,3542,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.00,0.0,0.00,0.00,11

In [ ]:
train = train.to_numpy()
test = test.to_numpy()

X_train, X_test,y_train,y_test = train_test_split(train, train[:,-1], test_size=0.9975, random_state=42, stratify=train[:,-1])

## **K-means and Spectral clustering**

### **K-Means**
To process the learning data, the K-means algorithm in data mining starts with a first group of randomly selected centroids, which are used as the beginning points for every cluster, and then performs iterative (repetitive) calculations to optimize the positions of the centroids

It halts creating and optimizing clusters when either:

    The centroids have stabilized — there is no change in their values because the clustering has been successful.
    The defined number of iterations has been achieved.

### **Spectral Clustering**
In spectral clustering, data points are treated as nodes of a graph. Thus, spectral clustering is a graph partitioning problem. The nodes are then mapped to a low-dimensional space that can be easily segregated to form clusters. No assumption is made about the shape/form of the clusters. The goal of spectral clustering is to cluster data that is connected but not necessarily compact or clustered within convex boundaries.
#### **Algorithm:**

Project data into Rn matrix
Define an Affinity matrix A , using a Gaussian Kernel K or an Adjacency matrix
Construct the Graph Laplacian from A (i.e. decide on a normalization)
Solve the Eigenvalue problem
Select k eigenvectors corresponding to the k lowest (or highest) eigenvalues to define a k-dimensional subspace
Form clusters in this subspace using k-means

In [ ]:
def kmeans(train, iterations, num_cluster):
  prev_centroid = None
  label = np.zeros(train.shape[0])
  for t in range(iterations):
    if t == 0:
      random.seed(42)
      index_ = random.sample(range(0, train.shape[0]), num_cluster)
      centroid = train[index_]
      distance = np.zeros((train.shape[0], centroid.shape[0]))
      
    else:
      prev_centroid = centroid
      for k in range(num_cluster):
        centroid[k] = np.mean(train[label==k], axis=0)

    for i in range(len(centroid)):
      distance[:, i] = np.linalg.norm(train - centroid[i], axis=1)

    label = np.argmin(distance, axis=1)

    if np.all(centroid == prev_centroid):
      break
  
  return centroid, label


def normalized_cut(train, iterations):
  # k_neighbour = 5
  for k in range(1, 12):
    dist_matrix = np.zeros((train.shape[0], train.shape[0]))
    for i in range(len(train)):
      dist_matrix[:,i] = np.linalg.norm((train-train[i]), axis=1)
    sim = kneighbors_graph(dist_matrix, k, mode='connectivity', include_self=False)
    sim = np.array(sim.toarray())

    degree_matrix = np.diag(np.sum(sim, axis=1))
    degree_inv = np.linalg.pinv(degree_matrix)
    L = degree_matrix - sim
    Laplacian = np.dot(degree_inv, L)

    eigen_values, eigen_vectors = np.linalg.eigh(Laplacian)
    idx = eigen_values.argsort()[::1]
    eigen_values = eigen_values[idx]
    eigen_vectors = eigen_vectors[:,idx]
    eigen_vectors = eigen_vectors[:,:11]

    Y = np.zeros((eigen_vectors.shape[0],eigen_vectors.shape[1]))
    for i in range(eigen_vectors.shape[0]) :
      Y[i] = eigen_vectors[i] / np.linalg.norm(eigen_vectors[i])
    
  centroids, cluster_assig = kmeans(Y, iterations, 11)
  
  return centroids, cluster_assig


def get_cluster_label(num_cluster, label):
  normal = np.zeros(num_cluster)
  for i in range(num_cluster):
    indices = np.where(label == i)[0]
    if np.any(indices) == False:
      normal[i] = -1
    else:
      points = train[indices]
      normal[i] = np.argmax(np.bincount(points[:,-1].astype(int)))

  return normal


def distance_centroid_test(test, centroid, normal):
  distance = np.zeros((test.shape[0], centroid.shape[0]))
  for i in range(len(centroid)):
    distance[:, i] = np.linalg.norm(test - centroid[i], axis=1)

  label = np.argmin(distance, axis=1)
  
  for i in range(label.shape[0]):
    label[i] = normal[label[i]]
    
  return label

## **Evaluation**

### **Purity (aka Precision)**

Precision is the ratio of the correctly +ve labeled by our program to all +ve labeled.
Precision answers the following: How many of those who we labeled as diabetic are actually diabetic?
Precision = TP/(TP+FP)
numerator: +ve labeled diabetic people.
denominator: all +ve labeled by our program (whether they’re diabetic or not in reality).
### **Recall (aka Sensitivity)**

Recall is the ratio of the correctly +ve labeled by our program to all who are diabetic in reality.
Recall answers the following question: Of all the people who are diabetic, how many of those we correctly predict?
Recall = TP/(TP+FN)
numerator: +ve labeled diabetic people.
denominator: all people who are diabetic (whether detected by our program or not)
### **F1-score (aka F-Score / F-Measure)**

F1 Score considers both precision and recall.
It is the harmonic mean(average) of the precision and recall.
F1 Score is best if there is some sort of balance between precision (p) & recall (r) in the system. Oppositely F1 Score isn’t so high if one measure is improved at the expense of the other.
For example, if P is 1 & R is 0, F1 score is 0.
F1 Score = 2*(Recall * Precision) / (Recall + Precision)

### **Conditional Entropy**
The conditional entropy of random variable Y given X X (i.e., conditioned by X X), denoted as H ( Y | X ) , is equal to H ( Y ) − I ( Y ; X ) where I ( Y ; X ) is the mutual information between Y and X X.

In [ ]:
def Purity(test_original_labels, test_clustering_labels):
  cont_mat = metrics.cluster.contingency_matrix(test_original_labels, test_clustering_labels)
  cont_mat = cont_mat.T
  cluster_purity = np.zeros((cont_mat.shape[0], 1))
  cluster_total = np.sum(cont_mat, axis = 1).reshape(cont_mat.shape[0], 1)

  for i in range(cont_mat.shape[0]):
    index_max = np.argmax(cont_mat[i])
    cluster_purity[i] = cont_mat[i][index_max] / np.sum(cont_mat[i])

  purity = np.dot(cluster_purity.T, cluster_total) / np.sum(cluster_total)
  return purity[0][0]


def Recall(test_original_labels, test_clustering_labels):
  cont_mat = metrics.cluster.contingency_matrix(test_original_labels, test_clustering_labels)
  cont_mat = cont_mat.T
  recall = np.zeros((cont_mat.shape[0], 1))
  cluster_total = np.sum(cont_mat, axis = 1).reshape(cont_mat.shape[0], 1)

  for i in range(cont_mat.shape[0]):
    index_max = np.argmax(cont_mat[i])
    recall[i] = cont_mat[i][index_max] / np.sum(cont_mat[:, index_max])

  recall_final = np.dot(recall.T, cluster_total) / np.sum(cluster_total)
  return recall_final[0][0]


def F_Measure(test_original_labels, test_clustering_labels):
  cont_mat = metrics.cluster.contingency_matrix(test_original_labels, test_clustering_labels)
  cont_mat = cont_mat.T
  precision = np.zeros((cont_mat.shape[0], 1))
  recall = np.zeros((cont_mat.shape[0], 1))

  for i in range(cont_mat.shape[0]):
      index_max = np.argmax(cont_mat[i])
      precision[i] = cont_mat[i][index_max] / np.sum(cont_mat[i])
      recall[i] = cont_mat[i][index_max] / np.sum(cont_mat[:, index_max])

  F_Measure = (2 * precision * recall) / (precision + recall)
  F_Measure_total = np.mean(F_Measure)
  return F_Measure_total


def Conditional_Entropy(test_original_labels, test_clustering_labels):
  cont_mat = metrics.cluster.contingency_matrix(test_original_labels, test_clustering_labels)
  cont_mat = cont_mat.T
  count_cluster = np.sum(cont_mat, axis = 1)
  total = np.sum(count_cluster)

  cont_entropy = np.where(np.copy(cont_mat) == 0, 1, np.copy(cont_mat))
  entropy_mat = np.zeros((cont_entropy.shape[0], 1))

  for i in range(cont_entropy.shape[0]):
      entropy_mat[i] = count_cluster[i] * np.sum(-cont_mat[i] * np.log10(cont_entropy[i] / np.sum(cont_mat[i]))) / np.sum(cont_mat[i])
  
  entropy = np.sum(entropy_mat) / total
  return entropy

## **Running code**

### **K-Means**

In [ ]:
iterations = 100
clusters = [3, 7, 10, 15, 23]

for i in clusters:
  centroid ,label_train = kmeans(train, iterations, i)
  normal = get_cluster_label(i, label_train)
  label_test = distance_centroid_test(test, centroid, normal)
  print('At K = ', i)
  print('Labels: ', label_test)

  purity = Purity(test[:, 41], label_test)
  recall = Recall(test[:, 41], label_test)
  fmeasure = F_Measure(test[:, 41], label_test)
  entropy = Conditional_Entropy(test[:, 41], label_test)
  print('Purity: ', purity)
  print('Recall: ', recall)
  print('F-measure: ', fmeasure)
  print('Entropy: ', entropy)

At K =  3
Labels:  [18 18 18 ... 18 18 18]
Purity:  0.5743091834046644
Recall:  0.9825945644760865
F-measure:  0.42110914661556337
Entropy:  0.4755958528998215
At K =  7
Labels:  [11 11  9 ... 11 11 11]
Purity:  0.7340599865206519
Recall:  0.7781324013563864
F-measure:  0.7076217995349054
Entropy:  0.29983140248584034
At K =  10
Labels:  [11 11  9 ... 11 11 11]
Purity:  0.845155132244722
Recall:  0.8940206080117801
F-measure:  0.8621865955258428
Entropy:  0.18388859875739347
At K =  15
Labels:  [18 18 18 ... 18 18 18]
Purity:  0.5613806410559051
Recall:  1.0
F-measure:  0.7190823637678302
Entropy:  0.4931477098412893
At K =  23
Labels:  [18 18 18 ... 18 18 18]
Purity:  0.5613806410559051
Recall:  1.0
F-measure:  0.7190823637678302
Entropy:  0.4931477098412893

### **Spectral clustering**

In [ ]:
iterations = 100

centroid, label_train = normalized_cut(X_train, iterations)
normal = get_cluster_label(12, label_train)
for i in range(label_train.shape[0]):
  label_train[i] = normal[label_train[i]]
print('Labels: ', label_train)

purity = Purity(X_train[:, 41], label_train)
recall = Recall(X_train[:, 41], label_train)
fmeasure = F_Measure(X_train[:, 41], label_train)
entropy = Conditional_Entropy(X_train[:, 41], label_train)
print('Purity: ', purity)
print('Recall: ', recall)
print('F-measure: ', fmeasure)
print('Entropy: ', entropy)

Labels:  [11 11 11 ... 11 11 11]
Purity:  0.5684210526315789
Recall:  1.0
F-measure:  0.7248322147651006
Entropy:  0.46869501972521854

## **Compare k-means and spectral clustering**

In [ ]:
iterations = 100
i = 11

centroid ,label_train = kmeans(X_train, iterations, i)
normal = get_cluster_label(i, label_train)
label_test = distance_centroid_test(test, centroid, normal)
print('At K = ', i)
print('Labels: ', label_test)

purity = Purity(test[:, 41], label_test)
recall = Recall(test[:, 41], label_test)
fmeasure = F_Measure(test[:, 41], label_test)
entropy = Conditional_Entropy(test[:, 41], label_test)
print('Purity: ', purity)
print('Recall: ', recall)
print('F-measure: ', fmeasure)
print('Entropy: ', entropy)

At K =  11
Labels:  [11 11 11 ... 11 11 11]
Purity:  0.5613806410559051
Recall:  1.0
F-measure:  0.7190823637678302
Entropy:  0.4931477098412893

## **Another implementation for clustering**

## **DBSCAN Algorithm**
To start off the algorithm, we choose a random point
It is time to introduce 2 major parameters for DBSCAN clustering.

    Epsilon

This is the radius of the circle that we must draw around our pointing focus.

    Minimum number of points

This is the number of points that we want in the neighbourhood of our point in focus (within the circle).

…continuing with the algorithm

We draw a circle of radius ‘epsilon’ around the chosen point and inspect the neighbourhood.

Now let’s suppose that we kept the ‘minimum points’ parameter to be 3. This is how it would matter.

There are few rules to follow here;

    A point is a ‘core point’ if its neighbouring points are greater than or equal to the minimum points we chose at the start.
    A point is a ‘border point’ if its neighbouring points are less than the minimum points we chose at the start.
    A point is considered ‘Noise’ if it has no points in its neighbourhood

In [ ]:
def distance(df_, p_,index,eps):
  df= np.array(df_)
  p= np.array(p_)
  
  result = []
  distance = 0
  for j in range(df.shape[0]):
    if j != index:
      for i in range(1, len(cols)):
        distance = distance + (df[j][i] - p[i])**2
      distance = (distance**0.5)
      if distance <=eps:
        result.append(df[j])

  return result

def check_core_point(eps,minPts, df, index):
  
  p = df.loc[index]
  temp = pd.DataFrame (distance(df,p,index,eps), columns = cols)

  #check how many points are present within radius
  if len(temp) >= minPts:
    #return format (dataframe, is_core, is_border, is_noise)
    return (temp.index , True, False, False)
  
  elif (len(temp) < minPts) and len(temp) > 0:
    #return format (dataframe, is_core, is_border, is_noise)
    return (temp.index , False, True, False)
  
  elif len(temp) == 0:
    #return format (dataframe, is_core, is_border, is_noise)
    return (temp.index , False, False, True)
    

def cluster_with_stack(eps, minPts, df):
  #initiating cluster number
  C = 1
  #initiating stacks to maintain
  current_stack = set()
  unvisited = list(df.index)
  clusters = []
  
  
  while (len(unvisited) != 0): #run until all points have been visited
    #identifier for first point of a cluster
    first_point = True
    
    #choose a random unvisited point
    current_stack.add(random.choice(unvisited))
    
    while len(current_stack) != 0: #run until a cluster is complete
        
      #pop current point from stack
      curr_idx = current_stack.pop()
      
      #check if point is core, neighbour or border
      neigh_indexes, iscore, isborder, isnoise = check_core_point(eps, minPts, df, curr_idx)
      
      #dealing with an edge case
      if (isborder & first_point):
        #for first border point, we label it aand its neighbours as noise 
        clusters.append((curr_idx, 0))
        clusters.extend(list(zip(neigh_indexes,[0 for _ in range(len(neigh_indexes))])))
        
        #label as visited
        unvisited.remove(curr_idx)
        unvisited = [e for e in unvisited if e not in neigh_indexes]

        continue
          
      unvisited.remove(curr_idx) #remove point from unvisited list
      
      
      neigh_indexes = set(neigh_indexes) & set(unvisited) #look at only unvisited points
      
      if iscore: #if current point is a core
        first_point = False
        
        clusters.append((curr_idx,C)) #assign to a cluster
        current_stack.update(neigh_indexes) #add neighbours to a stack

      elif isborder: #if current point is a border point
        clusters.append((curr_idx,C))
        
        continue

      elif isnoise: #if current point is noise
        clusters.append((curr_idx, 0))
        
        continue
           
    if not first_point:
      #increment cluster number
      C+=1


  cluster = np.array(clusters)
  return cluster[:, 1], C

In [ ]:
#radius of the circle
eps = 0.6
#minimum neighbouring points
minPts = 3
data = pd.DataFrame(X_train, columns = cols)
clustered, no_clusters = cluster_with_stack(eps, minPts, data)
normal = get_cluster_label(no_clusters, clustered)
for i in range(clustered.shape[0]):
  clustered[i] = normal[clustered[i]]
print('Labels: ',clustered)

purity = Purity(X_train[:, 41], clustered)
recall = Recall(X_train[:, 41], clustered)
fmeasure = F_Measure(X_train[:, 41], clustered)
entropy = Conditional_Entropy(X_train[:, 41], clustered)
print('Purity: ', purity)
print('Recall: ', recall)
print('F-measure: ', fmeasure)
print('Entropy: ', entropy)

Labels:  [11 11 11 ... 11 11 11]
Purity:  0.5684210526315789
Recall:  1.0
F-measure:  0.7248322147651006
Entropy:  0.46869501972521854